### ISSUE TITLE
TZ/Language

### ISSUE THREAD

**Issue by GreyMoth** [nanawel/reciphpes#25]
Thank you for your excellent project. I have tried everything I can think of to change the timezone and/or language: it seems to believe I speak French. Suggestion: GUI language change.

**Comment by nanawel** [comment]
You're right, I did not provide any way to set the language even server-wide.
It might be possible to do this by overriding a config file but I'm not sure.

I'll work on that.

**Comment by nanawel** [comment]
That should be fixed in the latest commits. Now [thanks to Symfony 5.4](https://symfony.com/blog/new-in-symfony-5-4-language-negotiation) the application uses the `Accept-Language` header sent by the browser to determine what language to use (but atm there are only 2: EN and FR).

A new Docker image is available at https://hub.docker.com/r/nanawel/reciphpes/tags for you to try.

**Comment by GreyMoth** [comment]
Nanawel, thank you! You did a good job: only a few things did not change.

* time of year (writing recipe)
* timestamp on a recipe

These are obviously not a big deal. I will not be using the time of year and the date/time is nit-picking.

I have numerous suggestions for enhancing reciphpes: if you are interested, would you prefer I place them all in one issue or one issue per idea? (which you are free to reject of course!) Of course, if you are not interested in giving this app additional attention, you have adequately changed it for my use: just let me know!

**Comment by nanawel** [comment]
Thanks :)

Sorry I missed this item in your ticket but for the TZ issue, it's not the app's business actually. The Docker container is using the UTC timezone by default (so even for me that's not right), but you can easily change this using an environment variable in your `docker-compose.yml`:

```yml
    ...
    environment:
      TZ: Asia/Tokyo
```

This won't change the values already stored in your database if you have any though.

For the other suggestions, I would prefer you to create one ticket per request.
I can promise I'll read each one of them, but nothing more :wink:
