### ISSUE TITLE
Suggestion: Return to work-in-progress

### ISSUE THREAD

**Issue by GreyMoth** [nanawel/reciphpes#30]
The ability to be working on a recipe, change tabs to look at tags (for example), and then return to the recipe you were working on without the data being lost.

(suggestion)

**Comment by nanawel** [comment]
I understand what you mean, but this is a feature that would be much too complex to provide when all browsers nowadays support opening an infinite number of tabs without altering the one you're working on.

It's particularly easy on desktop, but it can also be achieved on a mobile device with a long press on "Tags" in the main menu, then "Open in a new tab".
