### ISSUE TITLE
Suggestion: "add recipe" on top toolbar

### ISSUE THREAD

**Issue by GreyMoth** [nanawel/reciphpes#34]
Adding a 'create new recipe' icon on the top bar would enable you to create a recipe while on any tab.

(suggestion)

**Comment by nanawel** [comment]
It's already here in the `New` menu (here in French):

![image](https://user-images.githubusercontent.com/4866761/208852305-df9a1dfd-d367-4296-87e0-201d1fcad6a0.png)
